name: Test

on: [push, pull_request]

jobs:
  test:
    name: Check for print functions
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Check for print functions
        run: |
          if grep -r "print(" --include="*.gd" --exclude="multiplayer.gd" .; then
            echo "Found print functions in the codebase. Please remove them (except in multiplayer.gd)."
            exit 1
          else
            echo "No print functions found in checked files."
          fi
